// 확장된 M12 렌즈 데이터 - 비교 도구용
export interface ExpandedLens {
  id: string;
  name: string;
  manufacturer: string;
  focalLength: number; // mm
  aperture: string; // e.g., "F2.5"
  sensorFormat: string; // e.g., "1/2.3\""
  description: string;
  price?: string;
  category: "wide" | "standard" | "telephoto";
  fov?: number; // Field of View in degrees
  distortion?: string;
  bfl?: string; // Back Focal Length
}

export const expandedLenses: ExpandedLens[] = [
  // 광각 렌즈 (Wide Angle)
  {
    id: "arducam-1.6mm",
    name: "Arducam 1.6mm Ultra Wide",
    manufacturer: "Arducam",
    focalLength: 1.6,
    aperture: "F2.2",
    sensorFormat: "1/4\"",
    description: "초광각 렌즈, 극도의 광각 촬영",
    price: "$12-18",
    category: "wide",
    fov: 150,
    distortion: "8-12%",
    bfl: "1.2mm",
  },
  {
    id: "arducam-2.8mm",
    name: "Arducam 2.8mm Wide Angle",
    manufacturer: "Arducam",
    focalLength: 2.8,
    aperture: "F2.0",
    sensorFormat: "1/4\"",
    description: "광각 렌즈, 넓은 시야각",
    price: "$15-22",
    category: "wide",
    fov: 100,
    distortion: "5-8%",
    bfl: "2.0mm",
  },
  {
    id: "commonlands-3.6mm",
    name: "Commonlands 3.6mm Wide",
    manufacturer: "Commonlands",
    focalLength: 3.6,
    aperture: "F2.0",
    sensorFormat: "1/2.3\"",
    description: "저왜곡 광각 렌즈",
    price: "$25-35",
    category: "wide",
    fov: 90,
    distortion: "<2%",
    bfl: "2.5mm",
  },
  {
    id: "towin-4mm",
    name: "Towin 4mm Wide Angle",
    manufacturer: "Towin",
    focalLength: 4,
    aperture: "F2.5",
    sensorFormat: "1/3\"",
    description: "산업용 광각 렌즈",
    price: "$20-28",
    category: "wide",
    fov: 85,
    distortion: "3-5%",
    bfl: "2.8mm",
  },

  // 표준 렌즈 (Standard)
  {
    id: "arducam-6mm",
    name: "Arducam 6mm Standard",
    manufacturer: "Arducam",
    focalLength: 6,
    aperture: "F2.0",
    sensorFormat: "1/2.3\"",
    description: "표준 렌즈, 일반 감시용",
    price: "$15-25",
    category: "standard",
    fov: 65,
    distortion: "1-2%",
    bfl: "3mm",
  },
  {
    id: "commonlands-8mm",
    name: "Commonlands 8mm Standard",
    manufacturer: "Commonlands",
    focalLength: 8,
    aperture: "F2.5",
    sensorFormat: "1/2.3\"",
    description: "고품질 표준 렌즈",
    price: "$30-40",
    category: "standard",
    fov: 50,
    distortion: "<1%",
    bfl: "4mm",
  },
  {
    id: "towin-8mm",
    name: "Towin 8mm Standard",
    manufacturer: "Towin",
    focalLength: 8,
    aperture: "F2.5",
    sensorFormat: "1/3\"",
    description: "산업용 표준 렌즈",
    price: "$25-32",
    category: "standard",
    fov: 48,
    distortion: "1-2%",
    bfl: "4.2mm",
  },
  {
    id: "edmund-12mm",
    name: "Edmund Optics 12.5mm",
    manufacturer: "Edmund Optics",
    focalLength: 12.5,
    aperture: "F5.6",
    sensorFormat: "1/2.3\"",
    description: "고정밀 표준 렌즈",
    price: "$40-55",
    category: "standard",
    fov: 35,
    distortion: "<0.5%",
    bfl: "5.5mm",
  },

  // 망원 렌즈 (Telephoto)
  {
    id: "arducam-16mm",
    name: "Arducam 16mm Telephoto",
    manufacturer: "Arducam",
    focalLength: 16,
    aperture: "F2.4",
    sensorFormat: "1/2.3\"",
    description: "중거리 망원 렌즈",
    price: "$25-35",
    category: "telephoto",
    fov: 20,
    distortion: "<1%",
    bfl: "6mm",
  },
  {
    id: "arducam-25mm",
    name: "Arducam 25mm Telephoto",
    manufacturer: "Arducam",
    focalLength: 25,
    aperture: "F2.4",
    sensorFormat: "1/2.3\"",
    description: "중거리 망원 렌즈, 적절한 성능",
    price: "$30-40",
    category: "telephoto",
    fov: 13,
    distortion: "<1%",
    bfl: "5mm",
  },
  {
    id: "arducam-35mm",
    name: "Arducam 35mm Telephoto",
    manufacturer: "Arducam",
    focalLength: 35,
    aperture: "F2.4",
    sensorFormat: "1/2.3\"",
    description: "35mm 망원 렌즈, 적정 성능",
    price: "$35-45",
    category: "telephoto",
    fov: 9,
    distortion: "<1%",
    bfl: "6mm",
  },
  {
    id: "commonlands-50mm",
    name: "Commonlands CIL051 50mm",
    manufacturer: "Commonlands",
    focalLength: 50,
    aperture: "F2.5",
    sensorFormat: "1/2.3\"",
    description: "저왜곡 망원 렌즈, 최적의 장거리 성능",
    price: "$60-80",
    category: "telephoto",
    fov: 7,
    distortion: "<1%",
    bfl: "7mm",
  },
  {
    id: "ragecams-50mm",
    name: "RageCams 50mm Telephoto",
    manufacturer: "RageCams",
    focalLength: 50,
    aperture: "F2.8",
    sensorFormat: "M12 범용",
    description: "범용 50mm 망원 렌즈",
    price: "$50-70",
    category: "telephoto",
    fov: 7,
    distortion: "1-2%",
    bfl: "6.5mm",
  },
  {
    id: "edmund-75mm",
    name: "Edmund Optics 75mm Telephoto",
    manufacturer: "Edmund Optics",
    focalLength: 75,
    aperture: "F4.0",
    sensorFormat: "1/2.3\"",
    description: "극장거리 망원 렌즈",
    price: "$80-120",
    category: "telephoto",
    fov: 4.5,
    distortion: "<0.5%",
    bfl: "8mm",
  },
  {
    id: "towin-100mm",
    name: "Towin 100mm Ultra Telephoto",
    manufacturer: "Towin",
    focalLength: 100,
    aperture: "F5.6",
    sensorFormat: "1/2.3\"",
    description: "초극장거리 망원 렌즈",
    price: "$100-150",
    category: "telephoto",
    fov: 3,
    distortion: "<0.3%",
    bfl: "9mm",
  },
];
